#!/bin/sh
#Filename: shelldemo6 Author: Zeanur Rahaman Zeon
clear
echo "Would you like to see a joke (y/n)? \c"
read reply
if [ "$reply" = "y" ]
then
echo "Question: How many surrealists does it take to change a light
bulb?"
echo "Answer: Fish."
else
echo "Not in the mood for jokes? Never mind perhaps
another day."
fi
echo "\n\nHave a nice day."